### ISSUE TITLE
Cannot start docker

### ISSUE THREAD

**Issue by kbender84** [mbround18/foundryvtt-docker#245]
I try to start the image on unicloud server. The initial screen works fine, but after providing the timed URL I get following info in run.log

Launching FoundryVTT with: --dataPath=/foundrydata --port=4444 --hostname=foundry.vtt --noupnp --proxySSL
[PM2][Initialization] Environment variable HOME (Linux) or HOMEPATH (Windows) are not set!
[PM2][Initialization] Defaulting to /etc/.pm2
internal/validators.js:124
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:1110:7)
    at Object.instanciate (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/binaries/Runtime4Docker.js:66:47)
    at Command.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/binaries/Runtime4Docker.js:48:13)
    at Command.listener (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:315:8)
    at Command.emit (events.js:376:20)
    at Command.parseArgs (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:653:12)
    at Command.parse (/usr/local/share/.config/yarn/global/node_modules/commander/index.js:474:21)
    at Object.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/pm2/lib/binaries/Runtime4Docker.js:190:11)
    at Module._compile (internal/modules/cjs/loader.js:1068:30) {
  code: 'ERR_INVALID_ARG_TYPE'
}

**Comment by mbround18** [comment]
@kbender84 thats a unique error i have not seen before, i wonder if its an issue with pm2. Give me a couple days to do some debugging on this one. Any information you can provide? 

docker version, 
container version
etc...

**Comment by kbender84** [comment]
Hi, problem solved. I was trying to initize docker in Jelastic cloud. 
I have created Docker server in that cloud env and initiated the docker image. It works perfectly.
